<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'forms.required' => '<p class="note">Fields with <span class="required">*</span> are required.</p>',
  'forms.compareOperators' => '<p>You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.</p>',
  'forms.advancedSearch' => 'Advanced Search',
  'user.deleteConfirmation' => 'Are you sure you want to delete this item?',
  'models.vote.candidate' => 'Candidate',
  'menu.categories' => 'Categories',
  'models.category' => 'Category',
  'menu.category' => 'Category {category}',
  'footer.copyright' => 'Copyright &copy; {date} by David Madl.',
  'footer.silk' => 'Uses a <a href="http://www.famfamfam.com/lab/icons/silk/">Silk</a> favicon.',
  'menu.create' => 'Create',
  'menu.categories.create' => 'Create Category',
  'menu.users.create' => 'Create User',
  'user.create.button' => 'Create',
  'category.create.button' => 'Create',
  'models.vote.cycleWarning' => 'Cycle found in the chain of votes: {chain}. Please meet and discuss.',
  'menu.categories.delete' => 'Delete Category',
  'menu.users.delete' => 'Delete User',
  'models.email' => 'Email',
  'error' => 'Error',
  'models.realname' => 'Full name',
  'vote.greeting' => 'Hello, {realname}!',
  'vote.history' => 'History of my vote',
  'models.vote.candidateIncorrect' => 'Incorrect candidate.',
  'models.vote.categoryIncorrect' => 'Incorrect category.',
  'login.incorrect' => 'Incorrect username or password.',
  'menu.login' => 'Login',
  'login.button' => 'Login',
  'menu.logout' => 'Logout ({user})',
  'menu.manage' => 'Manage',
  'menu.categories.manageAll' => 'Manage Categories',
  'menu.categories.manageOne' => 'Manage Category',
  'menu.users.manageOne' => 'Manage User',
  'menu.users.manageAll' => 'Manage Users',
  'sidebar.operations' => 'Operations',
  'vote.ownWeight' => 'Responsibility',
  'models.password' => 'Password',
  'models.vote.reason' => 'Reason',
  'login.rememberMe' => 'Remember me next time',
  'user.save.button' => 'Save',
  'category.save.button' => 'Save',
  'search.button' => 'Search',
  'http.400' => 'Invalid request. Please do not repeat this request again.',
  'http.404' => 'The requested page does not exist.',
  'menu.update' => 'Update',
  'menu.categories.update' => 'Update Category',
  'menu.categories.updateOne' => 'Update Category {category}',
  'menu.users.update' => 'Update User',
  'users.updateOne' => 'Update User {user}',
  'vote.update.button' => 'Update vote',
  'models.username' => 'Username',
  'menu.users' => 'Users',
  'menu.categories.view' => 'View Category',
  'menu.users.viewAll' => 'View Users',
  'menu.users.viewOne' => 'View User {user}',
  'menu.viewCategoryVote' => 'View {category} Vote',
  'menu.vote' => 'Vote',
  'vote.button' => 'Vote',
  'menu.vote.again' => 'Vote again',
  'models.voteCount' => 'Vote count',
  'vote.votedFor' => 'Voted for',
  'vote.yetToVote' => 'Yet to vote for',
  'models.duplicate' => '{attribute} duplicate: {value} is already registered.',
  'menu.categoryVote' => '{category} Vote',
);
