<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'forms.required' => '<p class="note">Mit <span class="required">*</span> gekennzeichnete Felder sind Pflichtfelder.</p>',
  'forms.compareOperators' => '<p>Optional kann ein Vergleichsoperator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) am Anfang jedes Suchwertes benutzt werden, um einen bestimmten Vergleich durchzuführen.</p>',
  'forms.advancedSearch' => 'Erweiterte Suche',
  'user.deleteConfirmation' => 'Dieses Element löschen?',
  'models.vote.candidate' => 'Kandidat',
  'menu.categories' => 'Kategorien',
  'models.category' => 'Kategorie',
  'menu.category' => 'Kategorie {category}',
  'footer.copyright' => 'Copyright &copy; {date} by David Madl.',
  'footer.silk' => 'Benutzt ein <a href="http://www.famfamfam.com/lab/icons/silk/">Silk</a> Favicon.',
  'menu.create' => 'Erstellen',
  'user.create.button' => 'Erstellen',
  'category.create.button' => 'Erstellen',
  'menu.categories.create' => 'Kategorie erstellen',
  'menu.users.create' => 'Benutzer erstellen',
  'models.vote.cycleWarning' => 'Eine Schleife wurde in der Stimmenkette gefunden: {chain}. Bitte treffen und diskutieren.',
  'menu.categories.delete' => 'Kategorie löschen',
  'menu.users.delete' => 'Benutzer löschen',
  'models.email' => 'E-Mail',
  'error' => 'Fehler',
  'models.realname' => 'Voller Name',
  'vote.greeting' => 'Hallo, {realname}!',
  'vote.history' => 'Verlauf meiner Stimme',
  'models.vote.candidateIncorrect' => 'Falscher Kandidat.',
  'models.vote.categoryIncorrect' => 'Falsche Kategorie.',
  'login.incorrect' => 'Falscher Benutzername oder Passwort.',
  'menu.login' => 'Login',
  'login.button' => 'Login',
  'menu.logout' => 'Logout ({user})',
  'menu.manage' => 'Verwalten',
  'menu.categories.manageAll' => 'Kategorien verwalten',
  'menu.categories.manageOne' => 'Kategorie verwalten',
  'menu.users.manageOne' => 'Benutzer verwalten',
  'menu.users.manageAll' => 'Benutzer verwalten',
  'sidebar.operations' => 'Aktionen',
  'vote.ownWeight' => 'Verantwortung',
  'models.password' => 'Passwort',
  'models.vote.reason' => 'Begründung',
  'login.rememberMe' => 'Angemeldet bleiben',
  'user.save.button' => 'Speichern',
  'category.save.button' => 'Speichern',
  'search.button' => 'Suchen',
  'http.400' => 'Falsche Anfrage. Bitte Anfrage nicht wiederholen.',
  'http.404' => 'Die angefragte Seite konnte nicht gefunden werden.',
  'menu.update' => 'Bearbeiten',
  'menu.categories.update' => 'Kategorie bearbeiten',
  'menu.categories.updateOne' => 'Kategorie {category} bearbeiten',
  'menu.users.update' => 'Benutzer bearbeiten',
  'users.updateOne' => 'Benutzer {user} bearbeiten',
  'vote.update.button' => 'Stimme bearbeiten',
  'models.username' => 'Benutzername',
  'menu.users' => 'Benutzer',
  'menu.categories.view' => 'Kategorie anzeigen',
  'menu.users.viewAll' => 'Benutzer anzeigen',
  'menu.users.viewOne' => 'Benutzer {user} anzeigen',
  'menu.viewCategoryVote' => '{category}-Stimme anzeigen',
  'menu.vote' => 'Abstimmen',
  'vote.button' => 'Abstimmen',
  'menu.vote.again' => 'Neu abstimmen',
  'models.voteCount' => 'Anzahl Stimmen',
  'vote.votedFor' => 'Vergebene Stimmen',
  'vote.yetToVote' => 'Stimme zu vergeben',
  'models.duplicate' => '{attribute} doppelt: {value} ist bereits registriert.',
  'menu.categoryVote' => '{category}-Stimme',
);
