<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '<p class="note">Fields with <span class="required">*</span> are required.</p>' => '<p class="note">Mit <span class="required">*</span> gekennzeichnete Felder sind Pflichtfelder.</p>',
  '<p>You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.</p>' => '<p>Optional kann ein Vergleichsoperator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) am Anfang jedes Suchwertes benutzt werden, um einen bestimmten Vergleich durchzuführen.</p>',
  'Advanced Search' => 'Erweiterte Suche',
  'Are you sure you want to delete this item?' => 'Dieses Element löschen?',
  'Candidate' => 'Kandidat',
  'Categories' => 'Kategorien',
  'Category' => 'Kategorie',
  'Category {category}' => 'Kategorie {category}',
  'Copyright &copy; {date} by David Madl.' => 'Copyright &copy; {date} by David Madl.',
  'Create' => 'Erstellen',
  'Create Category' => 'Kategorie erstellen',
  'Create User' => 'Benutzer erstellen',
  'Cycle found in the chain of votes: {chain}. Please meet and discuss.' => 'Eine Schleife wurde in der Stimmenkette gefunden: {chain}. Bitte treffen und diskutieren.',
  'Delete Category' => 'Kategorie löschen',
  'Delete User' => 'Benutzer löschen',
  'Email' => 'E-Mail',
  'Error' => 'Fehler',
  'Full name' => 'Voller Name',
  'Hello, {realname}!' => 'Hallo, {realname}!',
  'History of my vote' => 'Verlauf meiner Stimme',
  'Incorrect candidate.' => 'Falscher Kandidat.',
  'Incorrect category.' => 'Falsche Kategorie.',
  'Incorrect username or password.' => 'Falscher Benutzername oder Passwort.',
  'Invalid request. Please do not repeat this request again.' => 'Falsche Anfrage. Bitte Anfrage nicht wiederholen.',
  'Login' => 'Login',
  'Logout ({user})' => 'Logout ({user})',
  'Manage' => 'Verwalten',
  'Manage Categories' => 'Kategorien verwalten',
  'Manage Category' => 'Kategorie verwalten',
  'Manage User' => 'Benutzer verwalten',
  'Manage Users' => 'Benutzer verwalten',
  'Operations' => 'Aktionen',
  'Own weight' => 'Eigene Gewichtung',
  'Password' => 'Passwort',
  'Reason' => 'Begründung',
  'Remember me next time' => 'Angemeldet bleiben',
  'Save' => 'Speichern',
  'Search' => 'Suchen',
  'The requested page does not exist.' => 'Die angefragte Seite konnte nicht gefunden werden.',
  'Update' => 'Bearbeiten',
  'Update Category' => 'Kategorie bearbeiten',
  'Update Category {category}' => 'Kategorie {category} bearbeiten',
  'Update User' => 'Benutzer bearbeiten',
  'Update User {user}' => 'Benutzer {user} bearbeiten',
  'Update vote' => 'Stimme bearbeiten',
  'Username' => 'Benutzername',
  'Users' => 'Benutzer',
  'View Category' => 'Kategorie anzeigen',
  'View User' => 'Benutzer anzeigen',
  'View User {user}' => 'Benutzer {user} anzeigen',
  'View {category} Vote' => '{category}-Stimme anzeigen',
  'Vote' => 'Abstimmen',
  'Vote again' => 'Neu abstimmen',
  'Vote count' => 'Anzahl Stimmen',
  'Voted for' => 'Vergebene Stimmen',
  'Yet to vote for' => 'Stimme zu vergeben',
  '{attribute} duplicate: {value} is already registered.' => '{attribute} doppelt: {value} ist bereits registriert.',
  '{category} Vote' => '{category}-Stimme',
);
