#!/bin/bash
#
# Git commit hook to update testing webserver folder in /http
#
# This file belongs in .git/hooks

# uncomment if not testing
#exit 0

echo David: testing mode - updating git repo in /http
cd /http/civi-repo
git checkout master
git pull /home/david/Projects/civicracy master
git checkout confidential
git pull /home/david/Projects/civicracy master
git pull /home/david/Projects/civicracy confidential
