#!/bin/bash
#
# Git commit hook to update testing webserver folder in /http
#
# This file belongs in .git/hooks

# uncomment if not testing
#exit 0

echo David: testing mode - updating git repo in /http
cd /http/civi-repo
git checkout master > /tmp/githook || cat /tmp/githook
git pull -r /home/david/Projects/civicracy master > /tmp/githook || cat /tmp/githook
git checkout confidential > /tmp/githook || cat /tmp/githook
git pull -r /home/david/Projects/civicracy master > /tmp/githook || cat /tmp/githook
git pull -r /home/david/Projects/civicracy confidential > /tmp/githook || cat /tmp/githook
