<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'category.create.button' => 'Erstellen',
  'category.save.button' => 'Speichern',
  'error' => 'Fehler',
  'forms.advancedSearch' => 'Erweiterte Suche',
  'forms.compareOperators' => '<p>Optional kann ein Vergleichsoperator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) am Anfang jedes Suchwertes benutzt werden, um einen bestimmten Vergleich durchzuführen.</p>',
  'forms.displayImported' => '<p>Folgende Benutzer wurden erfolgreich importiert: </p>',
  'forms.importCSVfile' => '<p>Das CSV File sollte mindestens zwei Spalten (Voller Name; E-Mail Adresse;) enthalten! Der Benutzername kann entweder als 3. Spalte angegeben werden oder wird aus dem vollen Namen ohne Leerzeichen erstellt!</p>',
  'forms.required' => '<p class="note">Mit <span class="required">*</span> gekennzeichnete Felder sind Pflichtfelder.</p>',
  'http.400' => 'Falsche Anfrage. Bitte Anfrage nicht wiederholen.',
  'http.404' => 'Die angefragte Seite konnte nicht gefunden werden.',
  'login.button' => 'Login',
  'login.incorrect' => 'Falscher Benutzername oder Passwort.',
  'login.rememberMe' => 'Angemeldet bleiben',
  'menu.categories' => 'Kategorien',
  'menu.categories.create' => 'Kategorie erstellen',
  'menu.categories.delete' => 'Kategorie löschen',
  'menu.users.displayImported' => 'Benutzer importieren',
  'menu.categories.manageAll' => 'Kategorien verwalten',
  'menu.categories.manageOne' => 'Kategorie verwalten',
  'menu.categories.update' => 'Kategorie bearbeiten',
  'menu.categories.updateOne' => 'Kategorie {category} bearbeiten',
  'menu.categories.view' => 'Kategorie anzeigen',
  'menu.category' => 'Kategorie {category}',
  'menu.categoryVote' => '{category}-Stimme',
  'menu.create' => 'Erstellen',
  'menu.users.import' => 'Benutzer importieren',
  'menu.login' => 'Login',
  'menu.logout' => 'Logout ({user})',
  'menu.manage' => 'Verwalten',
  'menu.settings' => 'Einstellungen',
  'menu.update' => 'Bearbeiten',
  'menu.users' => 'Benutzer',
  'menu.users.create' => 'Benutzer erstellen',
  'menu.users.delete' => 'Benutzer löschen',
  'menu.users.import' => 'Benutzer importieren',
  'menu.users.manageAll' => 'Benutzer verwalten',
  'menu.users.manageOne' => 'Benutzer verwalten',
  'menu.users.update' => 'Benutzer bearbeiten',
  'menu.users.viewAll' => 'Benutzer anzeigen',
  'menu.users.viewOne' => 'Benutzer {user} anzeigen',
  'menu.viewCategoryVote' => '{category}-Stimme anzeigen',
  'menu.vote' => 'Abstimmen',
  'menu.vote.again' => 'Neu abstimmen',
  'models.boardsize' => 'Ratsgröße',
  'models.category' => 'Kategorie',
  'models.description' => 'Beschreibung',
  'models.duplicate' => '{attribute} doppelt: {value} ist bereits registriert.',
  'models.email' => 'E-Mail',
  'models.password' => 'Passwort',
  'models.password.description' => 'Zum Behalten des alten Passwortes einfach leer lassen.',
  'models.slogan' => 'Slogan',
  'models.slogan.description' => 'Ein kurzer öffentlicher Wahlspruch, um sich besser von den anderen Kandidatinnen und Kandidaten abzugrenzen.',
  'models.realname' => 'Voller Name',
  'models.repeat_password' => 'Passwort wiederholen',
  'models.reset_password' => 'Passwort zurücksetzen',
  'models.username' => 'Benutzername',
  'models.vote.candidate' => 'Kandidat',
  'models.vote.candidateIncorrect' => 'Falscher Kandidat.',
  'models.vote.categoryIncorrect' => 'Falsche Kategorie.',
  'models.vote.reason' => 'Begründung',
  'models.voteCount' => 'Anzahl Stimmen',
  'search.button' => 'Suchen',
  'sidebar.operations' => 'Aktionen',
  'site.motto' => 'Demokratisch Entscheidungsträger finden',
  'timestamp.format' => 'd.m.Y H:i:s',
  'user.create.button' => 'Erstellen',
  'user.import.button' => 'Importieren',
  'user.csvselectfile.label' => 'Bitte lokales CSV File auswählen:',
  'user.deleteConfirmation' => 'Diese Person wirklich löschen?',
  'user.settings.saved' => '<div class="alert alert-success"><p>Einstellungen erfolgreich gespeichert.</p></div>',
  'user.registration.email' => '<p class="note">Das Passwort wird per E-Mail zugeschickt.</p>',
  'user.save.button' => 'Speichern',
  'users.updateOne' => 'Benutzer {user} bearbeiten',
  'vote.button' => 'Abstimmen',
  'vote.days' => 'Tage',
  'vote.explainVoting' => '<p>Entscheide, wem Du das Vertrauen schenkst! Die gewählte Person übernimmt deine gesamte Verantwortung (zusätzlich zur Verantwortung, die ihr schon von anderen weitergegeben wird).</p>',
  'vote.greeting' => 'Hallo, {realname}!',
  'vote.currentlyresult' => 'Momentane Verantwortungsverteilung',
  'voteresult.name' => 'Name',
  'voteresult.rank' => 'Rang',
  'voteresult.weightAbs' => 'Absolut',
  'voteresult.weightPer' => 'Prozentuell',
  'vote.noslogan' => '<em>kein Slogan</em>',
  'vote.participation' => 'Wahlbeteiligung',
  'vote.ownWeight' => 'Verantwortung',
  'vote.path' => 'Verlauf meiner Stimme',
  'vote.remaining' => 'verbleibend',
  'vote.update.button' => 'Stimme bearbeiten',
  'vote.votedFor' => 'Vergebene Stimmen',
  'vote.yetToVote' => 'Stimme zu vergeben',
  'voteresult.slogan' => 'Slogan',
  'vote.changeslogan.button' => 'Slogan ändern',
);
